### ISSUE TITLE
Unable to process integers

### ISSUE THREAD

**Issue by technotariat** [TylerPachal/npm-string-to-number#1]
I'm currently using string-to-number in a BDD project to manage numbers spelt out in Gherkin, such as `Given I attempt to log in with invalid credentials three times` and  `Given I attempt to log in with invalid credentials 3 times`.

On the second example the `convert()` function will return `undefined` instead of the integer `3`.

The reason I'm using the string-to-number library is to manage scenarios that will use a mixture of digit and string representations of numbers coming from non-technical people.

Is it possible to try and use `parseInt()` or `parseFloat()` before to manage this use case?

**Comment by TylerPachal** [comment]
Hi Colin, that is out of scope for this project.
